### ISSUE TITLE
crash

### ISSUE THREAD

**Issue by cddc22** [littleWhiteDuck/SimpleHook#1]
me.simpleHook
java.lang.OutOfMemoryError: Failed to allocate a 1600648 byte allocation with 413912 free bytes and 404KB until OOM, target footprint 268435456, growth limit 268435456
	at java.util.Arrays.copyOf(Arrays.java:3257)
	at java.lang.AbstractStringBuilder.ensureCapacityInternal(AbstractStringBuilder.java:124)
	at java.lang.AbstractStringBuilder.append(AbstractStringBuilder.java:596)
	at java.lang.StringBuffer.append(StringBuffer.java:367)
	at java.io.BufferedReader.readLine(BufferedReader.java:381)
	at java.io.BufferedReader.readLine(BufferedReader.java:400)
	at littleWhiteDuck.ۥ۫ۨ$ۦۖ۫.hasNext(:2)
	at android.support.v4.media.session.۫ۖۡ۟.ۨ۬ۙ(Unknown Source:8)
	at littleWhiteDuck.ۥۗۘ.ۦۖ۠(Unknown Source:152)
	at littleWhiteDuck.q9$ۦۖ۠.ۦۖۖ(:2)
	at littleWhiteDuck.ۦۢۨ.ۦۗۡ(:2)
	at littleWhiteDuck.ۦۚۥۥ.run(Unknown Source:86)
	at littleWhiteDuck.ۥ۬ۘ.run(Unknown Source:12)
	at littleWhiteDuck.qi.run(Unknown Source:2)
	at littleWhiteDuck.ۥۖ۟ۥ.ۦۖۘ(Unknown Source:0)
	at littleWhiteDuck.ۥۖ۟ۥ$ۦۖ۫.run(:5

**Comment by cddc22** [comment]
fix  by  noroot
