### ISSUE TITLE
[bug] 经常闪退崩溃 （1.3.4-24030222）

### ISSUE THREAD

**Issue by Homby** [littleWhiteDuck/SimpleHook#33]
报错日志如下

java.lang.RuntimeException: Unable to start activity ComponentInfo{me.simpleHook/me.simpleHook.ui.activity.ExtensionActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'boolean java.lang.Class.isInterface()' on a null object reference
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3825)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3971)
	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:101)
	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2389)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:210)
	at android.os.Looper.loop(Looper.java:299)
	at android.app.ActivityThread.main(ActivityThread.java:8261)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:559)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:954)
Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'boolean java.lang.Class.isInterface()' on a null object reference
	at java.lang.Class.isAssignableFrom(Class.java:589)
	at android.os.Parcel.readParcelableCreatorInternal(Parcel.java:4853)
	at android.os.Parcel.readParcelableInternal(Parcel.java:4766)
	at android.os.Parcel.readValue(Parcel.java:4532)
	at android.os.Parcel.readValue(Parcel.java:4312)
	at android.os.Parcel.-$$Nest$mreadValue(Unknown Source:0)
	at android.os.Parcel$LazyValue.apply(Parcel.java:4410)
	at android.os.Parcel$LazyValue.apply(Parcel.java:4369)
	at android.os.BaseBundle.getValueAt(BaseBundle.java:394)
	at android.os.BaseBundle.getValue(BaseBundle.java:374)
	at android.os.BaseBundle.getValue(BaseBundle.java:357)
	at android.os.BaseBundle.get(BaseBundle.java:696)
	at android.os.Bundle.getParcelable(Bundle.java:947)
	at littleWhiteDuck.ۦۙۡ.ۦۖۥ(SourceFile:1)
	at me.simpleHook.ui.activity.ExtensionActivity.onCreate(SourceFile:48)
	at android.app.Activity.performCreate(Activity.java:8516)
	at android.app.Activity.performCreate(Activity.java:8480)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1418)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3806)
	... 12 more

**Comment by 3091573329** [comment]
I have also encountered similar problems before
